apiVersion: apps/v1
kind: Deployment
metadata:
  name: development-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dev-app
  template:
    metadata:
      labels:
        app: dev-app
    spec:
      containers:
- name: dev-container
3
image: us-east4-docker.pkg.dev/qwiklabs-gcp-02-42d125dba997/my-repository/hello-cloudbuild-dev:v2.0
ports:
5
- containerPort: 8080
